# Generated by Django 5.2.14 on 2026-06-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_representatives', '0004_salesrepresentative_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='password',
        ),
    ]
